export const motivationalQuotes = [
    "The only bad workout is the one that didn't happen.",
    "Take care of your body. It's the only place you have to live.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "The groundwork for all happiness is good health.",
    "Fitness is not about being better than someone else. It's about being better than you used to be.",
    "A year from now you may wish you had started today.",
    "Discipline is doing what needs to be done, even if you don't want to do it.",
    "Success starts with self-discipline.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "Suffer the pain of discipline or suffer the pain of regret.",
    "Don't wish for a good body, work for it.",
    "Sweat is just fat crying.",
    "The hard part isn't getting your body in shape. The hard part is getting your mind in shape.",
    "Train insane or remain the same.",
    "Action may not always bring happiness, but there is no happiness without action.",
    "Don't stop when you're tired. Stop when you're done.",
    "You don't have to be great to start, but you have to start to be great.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "No pain, no gain. Shut up and train.",
    "Excuses don't burn calories.",
    "It's not about having time. It's about making time.",
    "Believe in yourself and all that you are.",
    "Strong is the new skinny.",
    "When you feel like quitting, think about why you started.",
    "Do something today that your future self will thank you for.",
    "Strive for progress, not perfection.",
    "Your health is an investment, not an expense.",
    "You are one workout away from a good mood.",
    "Making excuses burns zero calories per hour.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Slow progress is better than no progress.",
    "What seems impossible today will one day become your warm-up.",
    "Eat clean, train dirty.",
    "Don't count the days, make the days count.",
    "The difference between the impossible and the possible lies in a person's determination.",
    "Champions keep playing until they get it right.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If it doesn't challenge you, it doesn't change you.",
    "Push yourself because no one else is going to do it for you.",
    "Your body hears everything your mind says.",
    "Clear your mind of can't.",
    "Be stronger than your excuse.",
    "Fitness is like a relationship. You can't cheat and expect it to work.",
    "Respect your body. It’s the only one you get.",
    "Working out is a reward, not a punishment.",
    "Health is not about the weight you lose, but about the life you gain.",
    "Keep your squats low and your standards high.",
    "Running is cheaper than therapy.",
    "Exercise is a celebration of what your body can do.",
    "A healthy outside starts from the inside.",
    "Transform your body, transform your life.",
    "Don't let the scale define you.",
    "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.",
    "Fall in love with taking care of yourself.",
    "Every workout counts.",
    "Consistency is key.",
    "Rest properly so you can train properly.",
    "Nutrition is 80% of the battle.",
    "You can't out-train a bad diet.",
    "Drink more water.",
    "Sleep is the best meditation.",
    "Recovery is where the magic happens.",
    "Listen to your body.",
    "Focus on how you feel, not how you look.",
    "Celebrate every small victory.",
    "Stay patient and trust the journey.",
    "Rome wasn't built in a day, and neither is a healthy body.",
    "Set goals and crush them.",
    "Visualize your highest self and start showing up as her.",
    "Mindset is everything.",
    "Positive vibes only.",
    "Hustle for that muscle.",
    "Be the best version of you.",
    "Create healthy habits, not restrictions.",
    "Balance is the key to everything.",
    "Enjoy the process.",
    "Don't compare your Chapter 1 to someone else's Chapter 20.",
    "Stay focused and never give up.",
    "You are capable of amazing things.",
    "Dream big, work hard, stay humble.",
    "Make yourself proud.",
    "Be your own motivation.",
    "Today is another chance to get it right.",
    "Start where you are. Use what you have. Do what you can.",
    "The broken will become masters.",
    "Pain is temporary. Pride is forever.",
    "Hard work beats talent when talent doesn't work hard.",
    "Whatever you do, do it with all your heart.",
    "Be stubborn about your goals and flexible about your methods.",
    "A little progress each day adds up to big results.",
    "Invest in yourself.",
    "Discipline creates freedom.",
    "Willpower is a muscle. The more you use it, the stronger it gets.",
    "Challenges are what make life interesting. Overcoming them is what makes life meaningful.",
    "Energy flows where attention goes.",
    "Think positive, exercise daily, eat healthy, work hard, stay strong, worry less, dance more, love often, be happy.",
    "Your only limit is you.",
    "Go the extra mile. It's never crowded.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Believe you can and you're halfway there.",
    "Don't wait for opportunity. Create it.",
    "Great things never came from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Stay hungry. Stay foolish.",
    "Simplicity is the ultimate sophistication.",
    "Happiness depends upon ourselves."
];
